//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gatunek", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class Gatunek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_gatunekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_gatunek {
            get {
                return this.Id_gatunekField;
            }
            set {
                if ((this.Id_gatunekField.Equals(value) != true)) {
                    this.Id_gatunekField = value;
                    this.RaisePropertyChanged("Id_gatunek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa {
            get {
                return this.NazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwaField, value) != true)) {
                    this.NazwaField = value;
                    this.RaisePropertyChanged("Nazwa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producent", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class Producent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_producentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Rok_zalozeniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZalozycielField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_producent {
            get {
                return this.Id_producentField;
            }
            set {
                if ((this.Id_producentField.Equals(value) != true)) {
                    this.Id_producentField = value;
                    this.RaisePropertyChanged("Id_producent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa {
            get {
                return this.NazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwaField, value) != true)) {
                    this.NazwaField = value;
                    this.RaisePropertyChanged("Nazwa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Rok_zalozenia {
            get {
                return this.Rok_zalozeniaField;
            }
            set {
                if ((this.Rok_zalozeniaField.Equals(value) != true)) {
                    this.Rok_zalozeniaField = value;
                    this.RaisePropertyChanged("Rok_zalozenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zalozyciel {
            get {
                return this.ZalozycielField;
            }
            set {
                if ((object.ReferenceEquals(this.ZalozycielField, value) != true)) {
                    this.ZalozycielField = value;
                    this.RaisePropertyChanged("Zalozyciel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gry", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class Gry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Gatunek_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KrajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Ocena_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlatformaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Producent_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Rok_wydaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TytulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string link_okladkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gatunek_Id {
            get {
                return this.Gatunek_IdField;
            }
            set {
                if ((this.Gatunek_IdField.Equals(value) != true)) {
                    this.Gatunek_IdField = value;
                    this.RaisePropertyChanged("Gatunek_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kraj {
            get {
                return this.KrajField;
            }
            set {
                if ((object.ReferenceEquals(this.KrajField, value) != true)) {
                    this.KrajField = value;
                    this.RaisePropertyChanged("Kraj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ocena_Id {
            get {
                return this.Ocena_IdField;
            }
            set {
                if ((this.Ocena_IdField.Equals(value) != true)) {
                    this.Ocena_IdField = value;
                    this.RaisePropertyChanged("Ocena_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Platforma {
            get {
                return this.PlatformaField;
            }
            set {
                if ((this.PlatformaField.Equals(value) != true)) {
                    this.PlatformaField = value;
                    this.RaisePropertyChanged("Platforma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Producent_Id {
            get {
                return this.Producent_IdField;
            }
            set {
                if ((this.Producent_IdField.Equals(value) != true)) {
                    this.Producent_IdField = value;
                    this.RaisePropertyChanged("Producent_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Rok_wydania {
            get {
                return this.Rok_wydaniaField;
            }
            set {
                if ((this.Rok_wydaniaField.Equals(value) != true)) {
                    this.Rok_wydaniaField = value;
                    this.RaisePropertyChanged("Rok_wydania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tytul {
            get {
                return this.TytulField;
            }
            set {
                if ((object.ReferenceEquals(this.TytulField, value) != true)) {
                    this.TytulField = value;
                    this.RaisePropertyChanged("Tytul");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string link_okladka {
            get {
                return this.link_okladkaField;
            }
            set {
                if ((object.ReferenceEquals(this.link_okladkaField, value) != true)) {
                    this.link_okladkaField = value;
                    this.RaisePropertyChanged("link_okladka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string opis {
            get {
                return this.opisField;
            }
            set {
                if ((object.ReferenceEquals(this.opisField, value) != true)) {
                    this.opisField = value;
                    this.RaisePropertyChanged("opis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GryProdGatOc", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class GryProdGatOc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int eurogamer_comField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gry_online_plField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_gatunekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_ocenyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_producentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string krajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string link_okladkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int moja_ocenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwa_gatunkuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int platformaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string platformasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime rok_wydaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime rok_zalozeniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tytulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zalozycielField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int eurogamer_com {
            get {
                return this.eurogamer_comField;
            }
            set {
                if ((this.eurogamer_comField.Equals(value) != true)) {
                    this.eurogamer_comField = value;
                    this.RaisePropertyChanged("eurogamer_com");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gry_online_pl {
            get {
                return this.gry_online_plField;
            }
            set {
                if ((this.gry_online_plField.Equals(value) != true)) {
                    this.gry_online_plField = value;
                    this.RaisePropertyChanged("gry_online_pl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_gatunek {
            get {
                return this.id_gatunekField;
            }
            set {
                if ((this.id_gatunekField.Equals(value) != true)) {
                    this.id_gatunekField = value;
                    this.RaisePropertyChanged("id_gatunek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_oceny {
            get {
                return this.id_ocenyField;
            }
            set {
                if ((this.id_ocenyField.Equals(value) != true)) {
                    this.id_ocenyField = value;
                    this.RaisePropertyChanged("id_oceny");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_producent {
            get {
                return this.id_producentField;
            }
            set {
                if ((this.id_producentField.Equals(value) != true)) {
                    this.id_producentField = value;
                    this.RaisePropertyChanged("id_producent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kraj {
            get {
                return this.krajField;
            }
            set {
                if ((object.ReferenceEquals(this.krajField, value) != true)) {
                    this.krajField = value;
                    this.RaisePropertyChanged("kraj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string link_okladka {
            get {
                return this.link_okladkaField;
            }
            set {
                if ((object.ReferenceEquals(this.link_okladkaField, value) != true)) {
                    this.link_okladkaField = value;
                    this.RaisePropertyChanged("link_okladka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int moja_ocena {
            get {
                return this.moja_ocenaField;
            }
            set {
                if ((this.moja_ocenaField.Equals(value) != true)) {
                    this.moja_ocenaField = value;
                    this.RaisePropertyChanged("moja_ocena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nazwa {
            get {
                return this.nazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwaField, value) != true)) {
                    this.nazwaField = value;
                    this.RaisePropertyChanged("nazwa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nazwa_gatunku {
            get {
                return this.nazwa_gatunkuField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwa_gatunkuField, value) != true)) {
                    this.nazwa_gatunkuField = value;
                    this.RaisePropertyChanged("nazwa_gatunku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string opis {
            get {
                return this.opisField;
            }
            set {
                if ((object.ReferenceEquals(this.opisField, value) != true)) {
                    this.opisField = value;
                    this.RaisePropertyChanged("opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int platforma {
            get {
                return this.platformaField;
            }
            set {
                if ((this.platformaField.Equals(value) != true)) {
                    this.platformaField = value;
                    this.RaisePropertyChanged("platforma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string platformas {
            get {
                return this.platformasField;
            }
            set {
                if ((object.ReferenceEquals(this.platformasField, value) != true)) {
                    this.platformasField = value;
                    this.RaisePropertyChanged("platformas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime rok_wydania {
            get {
                return this.rok_wydaniaField;
            }
            set {
                if ((this.rok_wydaniaField.Equals(value) != true)) {
                    this.rok_wydaniaField = value;
                    this.RaisePropertyChanged("rok_wydania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime rok_zalozenia {
            get {
                return this.rok_zalozeniaField;
            }
            set {
                if ((this.rok_zalozeniaField.Equals(value) != true)) {
                    this.rok_zalozeniaField = value;
                    this.RaisePropertyChanged("rok_zalozenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tytul {
            get {
                return this.tytulField;
            }
            set {
                if ((object.ReferenceEquals(this.tytulField, value) != true)) {
                    this.tytulField = value;
                    this.RaisePropertyChanged("tytul");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zalozyciel {
            get {
                return this.zalozycielField;
            }
            set {
                if ((object.ReferenceEquals(this.zalozycielField, value) != true)) {
                    this.zalozycielField = value;
                    this.RaisePropertyChanged("zalozyciel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Oceny", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class Oceny : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EurogamerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Gry_online_plField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ocenyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Moja_ocenaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Eurogamer {
            get {
                return this.EurogamerField;
            }
            set {
                if ((this.EurogamerField.Equals(value) != true)) {
                    this.EurogamerField = value;
                    this.RaisePropertyChanged("Eurogamer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gry_online_pl {
            get {
                return this.Gry_online_plField;
            }
            set {
                if ((this.Gry_online_plField.Equals(value) != true)) {
                    this.Gry_online_plField = value;
                    this.RaisePropertyChanged("Gry_online_pl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_oceny {
            get {
                return this.Id_ocenyField;
            }
            set {
                if ((this.Id_ocenyField.Equals(value) != true)) {
                    this.Id_ocenyField = value;
                    this.RaisePropertyChanged("Id_oceny");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Moja_ocena {
            get {
                return this.Moja_ocenaField;
            }
            set {
                if ((this.Moja_ocenaField.Equals(value) != true)) {
                    this.Moja_ocenaField = value;
                    this.RaisePropertyChanged("Moja_ocena");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dodajGatunek", ReplyAction="http://tempuri.org/IService1/dodajGatunekResponse")]
        void dodajGatunek(Client.ServiceReference1.Gatunek g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dodajGatunek", ReplyAction="http://tempuri.org/IService1/dodajGatunekResponse")]
        System.Threading.Tasks.Task dodajGatunekAsync(Client.ServiceReference1.Gatunek g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edytujGatunek", ReplyAction="http://tempuri.org/IService1/edytujGatunekResponse")]
        void edytujGatunek(Client.ServiceReference1.Gatunek g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edytujGatunek", ReplyAction="http://tempuri.org/IService1/edytujGatunekResponse")]
        System.Threading.Tasks.Task edytujGatunekAsync(Client.ServiceReference1.Gatunek g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usunGatunek", ReplyAction="http://tempuri.org/IService1/usunGatunekResponse")]
        void usunGatunek(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usunGatunek", ReplyAction="http://tempuri.org/IService1/usunGatunekResponse")]
        System.Threading.Tasks.Task usunGatunekAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dodajProducenta", ReplyAction="http://tempuri.org/IService1/dodajProducentaResponse")]
        void dodajProducenta(Client.ServiceReference1.Producent p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dodajProducenta", ReplyAction="http://tempuri.org/IService1/dodajProducentaResponse")]
        System.Threading.Tasks.Task dodajProducentaAsync(Client.ServiceReference1.Producent p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edytujProducenta", ReplyAction="http://tempuri.org/IService1/edytujProducentaResponse")]
        void edytujProducenta(Client.ServiceReference1.Producent p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edytujProducenta", ReplyAction="http://tempuri.org/IService1/edytujProducentaResponse")]
        System.Threading.Tasks.Task edytujProducentaAsync(Client.ServiceReference1.Producent p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usunProducenta", ReplyAction="http://tempuri.org/IService1/usunProducentaResponse")]
        void usunProducenta(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usunProducenta", ReplyAction="http://tempuri.org/IService1/usunProducentaResponse")]
        System.Threading.Tasks.Task usunProducentaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dodajGre", ReplyAction="http://tempuri.org/IService1/dodajGreResponse")]
        void dodajGre(Client.ServiceReference1.Gry g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dodajGre", ReplyAction="http://tempuri.org/IService1/dodajGreResponse")]
        System.Threading.Tasks.Task dodajGreAsync(Client.ServiceReference1.Gry g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edytujGre", ReplyAction="http://tempuri.org/IService1/edytujGreResponse")]
        void edytujGre(Client.ServiceReference1.Gry g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edytujGre", ReplyAction="http://tempuri.org/IService1/edytujGreResponse")]
        System.Threading.Tasks.Task edytujGreAsync(Client.ServiceReference1.Gry g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usunGre", ReplyAction="http://tempuri.org/IService1/usunGreResponse")]
        void usunGre(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/usunGre", ReplyAction="http://tempuri.org/IService1/usunGreResponse")]
        System.Threading.Tasks.Task usunGreAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wyswietlGry", ReplyAction="http://tempuri.org/IService1/wyswietlGryResponse")]
        Client.ServiceReference1.GryProdGatOc[] wyswietlGry();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wyswietlGry", ReplyAction="http://tempuri.org/IService1/wyswietlGryResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GryProdGatOc[]> wyswietlGryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dodajOcene", ReplyAction="http://tempuri.org/IService1/dodajOceneResponse")]
        void dodajOcene(Client.ServiceReference1.Oceny o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dodajOcene", ReplyAction="http://tempuri.org/IService1/dodajOceneResponse")]
        System.Threading.Tasks.Task dodajOceneAsync(Client.ServiceReference1.Oceny o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edytujOcene", ReplyAction="http://tempuri.org/IService1/edytujOceneResponse")]
        void edytujOcene(Client.ServiceReference1.Oceny o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edytujOcene", ReplyAction="http://tempuri.org/IService1/edytujOceneResponse")]
        System.Threading.Tasks.Task edytujOceneAsync(Client.ServiceReference1.Oceny o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wyswietlGre", ReplyAction="http://tempuri.org/IService1/wyswietlGreResponse")]
        Client.ServiceReference1.GryProdGatOc[] wyswietlGre(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wyswietlGre", ReplyAction="http://tempuri.org/IService1/wyswietlGreResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GryProdGatOc[]> wyswietlGreAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ustawPlatforme", ReplyAction="http://tempuri.org/IService1/ustawPlatformeResponse")]
        void ustawPlatforme(Client.ServiceReference1.GryProdGatOc[] lst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ustawPlatforme", ReplyAction="http://tempuri.org/IService1/ustawPlatformeResponse")]
        System.Threading.Tasks.Task ustawPlatformeAsync(Client.ServiceReference1.GryProdGatOc[] lst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wyswietlProducentow", ReplyAction="http://tempuri.org/IService1/wyswietlProducentowResponse")]
        Client.ServiceReference1.Producent[] wyswietlProducentow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wyswietlProducentow", ReplyAction="http://tempuri.org/IService1/wyswietlProducentowResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.Producent[]> wyswietlProducentowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wyswietlGatunki", ReplyAction="http://tempuri.org/IService1/wyswietlGatunkiResponse")]
        Client.ServiceReference1.Gatunek[] wyswietlGatunki();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/wyswietlGatunki", ReplyAction="http://tempuri.org/IService1/wyswietlGatunkiResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.Gatunek[]> wyswietlGatunkiAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1>, Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void dodajGatunek(Client.ServiceReference1.Gatunek g) {
            base.Channel.dodajGatunek(g);
        }
        
        public System.Threading.Tasks.Task dodajGatunekAsync(Client.ServiceReference1.Gatunek g) {
            return base.Channel.dodajGatunekAsync(g);
        }
        
        public void edytujGatunek(Client.ServiceReference1.Gatunek g) {
            base.Channel.edytujGatunek(g);
        }
        
        public System.Threading.Tasks.Task edytujGatunekAsync(Client.ServiceReference1.Gatunek g) {
            return base.Channel.edytujGatunekAsync(g);
        }
        
        public void usunGatunek(int id) {
            base.Channel.usunGatunek(id);
        }
        
        public System.Threading.Tasks.Task usunGatunekAsync(int id) {
            return base.Channel.usunGatunekAsync(id);
        }
        
        public void dodajProducenta(Client.ServiceReference1.Producent p) {
            base.Channel.dodajProducenta(p);
        }
        
        public System.Threading.Tasks.Task dodajProducentaAsync(Client.ServiceReference1.Producent p) {
            return base.Channel.dodajProducentaAsync(p);
        }
        
        public void edytujProducenta(Client.ServiceReference1.Producent p) {
            base.Channel.edytujProducenta(p);
        }
        
        public System.Threading.Tasks.Task edytujProducentaAsync(Client.ServiceReference1.Producent p) {
            return base.Channel.edytujProducentaAsync(p);
        }
        
        public void usunProducenta(int id) {
            base.Channel.usunProducenta(id);
        }
        
        public System.Threading.Tasks.Task usunProducentaAsync(int id) {
            return base.Channel.usunProducentaAsync(id);
        }
        
        public void dodajGre(Client.ServiceReference1.Gry g) {
            base.Channel.dodajGre(g);
        }
        
        public System.Threading.Tasks.Task dodajGreAsync(Client.ServiceReference1.Gry g) {
            return base.Channel.dodajGreAsync(g);
        }
        
        public void edytujGre(Client.ServiceReference1.Gry g) {
            base.Channel.edytujGre(g);
        }
        
        public System.Threading.Tasks.Task edytujGreAsync(Client.ServiceReference1.Gry g) {
            return base.Channel.edytujGreAsync(g);
        }
        
        public void usunGre(int id) {
            base.Channel.usunGre(id);
        }
        
        public System.Threading.Tasks.Task usunGreAsync(int id) {
            return base.Channel.usunGreAsync(id);
        }
        
        public Client.ServiceReference1.GryProdGatOc[] wyswietlGry() {
            return base.Channel.wyswietlGry();
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GryProdGatOc[]> wyswietlGryAsync() {
            return base.Channel.wyswietlGryAsync();
        }
        
        public void dodajOcene(Client.ServiceReference1.Oceny o) {
            base.Channel.dodajOcene(o);
        }
        
        public System.Threading.Tasks.Task dodajOceneAsync(Client.ServiceReference1.Oceny o) {
            return base.Channel.dodajOceneAsync(o);
        }
        
        public void edytujOcene(Client.ServiceReference1.Oceny o) {
            base.Channel.edytujOcene(o);
        }
        
        public System.Threading.Tasks.Task edytujOceneAsync(Client.ServiceReference1.Oceny o) {
            return base.Channel.edytujOceneAsync(o);
        }
        
        public Client.ServiceReference1.GryProdGatOc[] wyswietlGre(int id) {
            return base.Channel.wyswietlGre(id);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GryProdGatOc[]> wyswietlGreAsync(int id) {
            return base.Channel.wyswietlGreAsync(id);
        }
        
        public void ustawPlatforme(Client.ServiceReference1.GryProdGatOc[] lst) {
            base.Channel.ustawPlatforme(lst);
        }
        
        public System.Threading.Tasks.Task ustawPlatformeAsync(Client.ServiceReference1.GryProdGatOc[] lst) {
            return base.Channel.ustawPlatformeAsync(lst);
        }
        
        public Client.ServiceReference1.Producent[] wyswietlProducentow() {
            return base.Channel.wyswietlProducentow();
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.Producent[]> wyswietlProducentowAsync() {
            return base.Channel.wyswietlProducentowAsync();
        }
        
        public Client.ServiceReference1.Gatunek[] wyswietlGatunki() {
            return base.Channel.wyswietlGatunki();
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.Gatunek[]> wyswietlGatunkiAsync() {
            return base.Channel.wyswietlGatunkiAsync();
        }
    }
}
